### ISSUE TITLE
Possibly revert commit 0deadf1d4d6ffb34688807a5fa983cf4ad2352ab (creality patches to toolhead.py)

### ISSUE THREAD

**Issue by sakitume** [K1-Klipper/klipper#11]
As discussed in D3vil Designs discord: https://discord.com/channels/1154500511777693819/1187303256335056956/1187810676903792740

The commit can be viewed here: https://github.com/Klipper3d/klipper/commit/0deadf1d4d6ffb34688807a5fa983cf4ad2352ab

It's possible this patch isn't absolutely necessary. What we know however is that it triggers a latent bug in HappyHare, or is a bug in itself (somehow) that HappyHare triggers.

So this issue is mostly a reminder until we can further investigate. When things are less experimental I will contact HappyHare developer and ask his opinion if it might be a HappyHare issue.

**Comment by sbtoonz** [comment]
Pending some feedback from a discord user
Will update issue and commit status once feedback is gathered

**Comment by sbtoonz** [comment]
https://github.com/K1-Klipper/klipper/commit/9446f72e8be688184c92948c3ccc07aff26952df

**Comment by sbtoonz** [comment]
3 users confirmed reverting this commit has 0 impact on probing and bed mesh

Reverted commit to maintain future integration compatibility with happy hare
