### ISSUE TITLE
Commit  34478db breaks something

### ISSUE THREAD

**Issue by mericon** [K1-Klipper/klipper#14]
23:26
Error evaluating 'gcode_macro _IF_HOME_Z:gcode': jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'z_pos'
23:26
Error evaluating 'gcode_macro _IF_HOME_Z:gcode': jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'z_pos'
23:26
Error evaluating 'gcode_macro _IF_HOME_Z:gcode': jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'z_pos'
23:26
Error evaluating 'gcode_macro _IF_HOME_Z:gcode': jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'z_pos'
23:26
Error evaluating 'gcode_macro _IF_HOME_Z:gcode': jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'z_pos'

**Comment by sbtoonz** [comment]
https://github.com/K1-Klipper/klipper/blob/master/klippy/extras/bed_mesh.py#L167-L173

**Comment by sbtoonz** [comment]
https://github.com/K1-Klipper/klipper/commit/32891381eda373110d9a813a9d9198ffd1061cba

**Comment by sbtoonz** [comment]
This is due to sensorless.cfg referencing z_pos 

please use sensorless.cfg found at 
https://github.com/K1-Klipper/installer_script_k1_and_max/raw/main/sensorless.cfg
