### ISSUE TITLE
Repo keeps appearing as dirty.

### ISSUE THREAD

**Issue by K2AAE** [K1-Klipper/klipper#30]
Repo is dirty. Detected the following modifed files: ['.gitignore']
Unofficial remote url: https://github.com/K1-Klipper/klipper.git
Repo has untracked source files: ['klippy/extras/gcode_shell_command.py']

After telling Klipper to fix it it the system stops working requiring a completed reinstall, after the reinstall the git becomes corrupt within a few hours.

**Comment by sbtoonz** [comment]
This is not a fault of the repo and will happen on any printer in any klipper install when you install files that are not tracked by the repository
